Sql
gaelleDijon/projet-data-warehouse pull request #2
Opened 2023-11-11 09:00 UTC by gaelleDijon

2023-11-11 10:12 UTC, charlotte-waegeneire commented on dags/sql/create-table.sql
> +    num_dep VARCHAR(2) UNIQUE NOT NULL PRIMARY KEY,
VARCHAR(3) instead of 2 for DOMTOM

2023-11-11 10:13 UTC, charlotte-waegeneire commented on dags/sql/create-table.sql
> +    departement VARCHAR(2) NOT NULL,
:warning: same, `VARCHAR(3)`

2023-11-11 10:14 UTC, charlotte-waegeneire commented on dags/sql/create-table.sql
> +    id_region VARCHAR(10),
should be an `INTEGER` to be a foreign key

2023-11-11 10:15 UTC, charlotte-waegeneire requested changes
SQL query not working - check my comments and discord messages for further explanations :woman_dancing:

2023-11-12 16:48 UTC, gaelleDijon commented
changes done

2023-11-12 19:18 UTC, charlotte-waegeneire approved these changes
perfect !

2023-11-12 19:19 UTC, merged